# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
RUN npm install --production --ignore-scripts

# Bundle app source
COPY index.js ./
COPY lib ./lib

# Default command
env NPM_CONFIG_LOGLEVEL warn
ENTRYPOINT ["node", "index.js"]
